Add sudt and acp contract info for mainnet
nervosnetwork/rfcs pull request #202
Opened 2020-08-31 02:54 UTC by duanyytop

2020-09-04 03:47 UTC, xxuejie approved these changes

2020-09-04 04:02 UTC, doitian commented on rfcs/0024-ckb-system-script-list/0024-ckb-system-script-list.md
> +| `tx_hash`   | `0xa05f28c9b867f8c5682039c10d8e864cf661685252aa74a008d255c33813bb81` |
Tips for reviewers:

Decoded dep group of the cell 0xa05f28c9b867f8c5682039c10d8e864cf661685252aa74a008d255c33813bb81.outputs[0x0]

```
$ ckb-cli molecule decode --type OutPointVec --binary-hex 0x02000000d032647ee7b5e7e28e73688d80ffc5fba306ee216ca43be4a762ec7e989a3daa00000000e2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c03000000
items:
  - index: 0x0
    tx_hash: 0xd032647ee7b5e7e28e73688d80ffc5fba306ee216ca43be4a762ec7e989a3daa
  - index: 0x3
    tx_hash: 0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c
```

2020-09-04 04:19 UTC, doitian commented on rfcs/0024-ckb-system-script-list/0024-ckb-system-script-list.md
> +| `tx_hash`   | `0xa05f28c9b867f8c5682039c10d8e864cf661685252aa74a008d255c33813bb81` |
0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c.outputs[0x3] ([located in explorer](https://explorer.nervos.org/transaction/0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c#3)) is the secp256k1 data cell  ([located in ckb/hashes.toml](https://github.com/nervosnetwork/ckb/blob/6caf504268a77b34891dd27fda393542b9b1938f/docs/hashes.toml#L22-L26))

0xd032647ee7b5e7e28e73688d80ffc5fba306ee216ca43be4a762ec7e989a3daa.outputs[0x0] ([located in explorer](https://explorer.nervos.org/transaction/0xd032647ee7b5e7e28e73688d80ffc5fba306ee216ca43be4a762ec7e989a3daa#0)) is the acp script, which data hash can be verified using `ckb-cli util blake2b`

<details>
<summary>ckb-cli util blake2b acp data hash</summary>

The output is expected to be `0x0fb343953ee78c9986b091defb6252154e0bb51044fd2879fde5b27314506111`

```
ckb-cli util blake2b --binary-hex  "0x7f454c460201010000000000000000000200f30001000000fe00010000000000400000000000000050d80000000000000100000040003800020040000c000b00010000000500000000000000000000000000010000000000000001000000000060c900000000000060c90000000000000010000000000000010000000600000000d000000000000000d001000000000000d0010000000000a807000000000000e00700000000000000100000000000005d7110082c00281086e4efc0001601c5a660616182804800efc0400875f9924789c72810efb0a05ee5b7c26562662265efb0d036f1bfb70700009387070099c737c50100130525506fc0e03f828097d1000093812172138581f8138601fc098e8145efc0603217c500001305053e19c517c500001305253eefc0e03cefc0a02602452c000146eff0bff76fc0e023138781f6938781f6638be700370300001303030063050300138581f602838280938581f6938781f69d8d8d858947b3c5f50291c9370300001303030063050300138581f60283828003c781f815eb411122e006e43e84eff0bffab70700009387070081cb75651305050097000000e700000085472384f1f8a2600264410182808280b70700009387070091cf75654111938501f91305050006e497000000e7000000a26041016ff0bff74971a2f2130600082a840a8586f6a6eecaeacee6d2e256fe5afa5ef662f266ee6aea6ee6efc06021a285130600040801efc0a0208a720a6982652a7daa6416992e99c2656a7cea69ea94ae94c275e2993060ae99b7c5010083b5055d3346c90034642d8eb7c5010083b5055eca7cca63027ea58e3868ad8eb7c5010083b5055fe693f29333c7e3003c6c2d8fb7c5010083b50560b3c7f90093180602ad8f939507028193cd8fb7c5010083ba855db7c5010003ba855eb7c5010083bb855fb7c5010003bb85600192336616013e9b334c6c0193558c01221c336cbc00a265b29ab3c252012e99e2651398060293d88201ae94a2758192a212ae93e27513150702b3e60601b3e21201ae990193498f369a1699e299ba9b334d4d013346c900b3c7f900b3cc7c0113588d019358060193d50701221d4216c21713d58c01336d0d0133661601cd8fa21cc67eb3ecac00ea94b29a3e9be693a58eb3c25a00334c8b0133c7e30013d80601939f120093151c00c21693d2f203135cfc032663c66813550701b3e60601b3e2f2010668336cbc00f69986754217498f9699ba9b33c7e900ae93931507020193369ab3cc9b01e2934d8f334daa0113951c00b3c6d3003a9a93dcfc03b3ecac00b3425a0013950602c6948192131f1d00e694c98e93d58201135dfd03a2122675336ded01258eb69ab3e2b2004299e6656a99131f060233cc8a010192b347f9003366e601135f8c01221c939f0702336cec01ae94aa93e6758193b3e7f701e293be9bb3c6d30033cdab0113df0601ae99c216329b935d8d019699b3e6e601221db34c9b01336dbd0133c7e900b69a1a9993df8c016a999355070133cc8a01a21c4217b3ecfc01b347f9004d8f131f1c00135cfc03e69493dd07013a9a336cec01aa99c217258eb3e7b701b3425a00e299935f0601be9b93951200b3c7f900421693d2f2033366f601b3e2b200939507028193329bcd8fb34c9b013e9b334c8b0193558c01221c939f1c00336cbc0093dcfc03e675b3ecfc019a93e69333c7e300ae93c275769933cdab01ae99e2991699b3c7f900931d1d003346c90093d50701135dfd03c217336dbd01cd8f931d0602f2940192ea943366b6013e9ba58eb29a334c8b01939f0602b3c25a0093151c008192135cfc03b3e6f60193dd8201336cbc00a212a265369ab3e2b2014699131f0702334daa01169901933367e701935f8d013346c900221d2e998265ba9b336dfd01c294b3cc9b01ea9413df8c01a58ea21cae94e665b3ecec01935d06014216e6933366b60133c7e300b29aae93a275b3c25a00939d120093d2f203135f0701b3e2b201ae9942173367e701969993df0601ba9bc21633c7e900b3e6f601931507020193369a4d8f334daa013a9ab3425a0093d58201a212931f1d00b3e2b200135dfd038675336dfd01b3cc9b016a99139f1c00b347f90093dcfc032e99c265b3ecec01e694258eae94e275e293b3c6d300ae93e265939d07028193ae99969933c7e9009355070142174d8fb3e7b7013a9abe9bb3425a00931f0602139f060233cdab01939512000192819293d2f2033366f601b3e6e601935d8d01b3e2b200221de665329bb69a336dbd01b34c9b0133cc8a016a9993df8c01135f8c01b347f900a21c2e99221c8675b3ecfc01336cec01e694e293258eb3c6d300ae94a27513df0601c216b3e6e601b69aae93e67533cc8a01131f1c00135cfc0393dd0701336cec01ae99c217b3e7b701e299935f0601be9b4216b3c7f9003366f601939507028193329bcd8fb34c9b013e9b334c8b0133cdab01169993558c01221c931d1d003346c900336cbc00135dfd038265336dbd01931d06020192939f1c00ea943366b60193dcfc03b3ecfc01a58eb29aae94aa99c265e693b3c25a00e29933c7e30093dd8201b3c7f900a212131f0702b3e2b2014299ae93019393d50701c217939f06023367e7011699cd8f8192b3e6f601ba9b3346c9003e9b369ab3cc9b01935d0601334c8b014216334daa0113df8c013366b60193151c00a21c135cfc03935f8d01b3ecec01b29a336cbc00221de265336dfd01e693b3c25a00ea9433c7e300939d120093d2f203a58e135f0701b3e2b201ae949a99e27542173367e701969993df0601ba9bc21633c7e900b3e6f601ae93931507020193369a4d8f334daa013a9ab3425a00b3cc9b0193d58201a212139f1c00b3e2b20093dcfc03c275b3ecec01e694931f1d00258ef299ae94135dfd03a265336dfd01969946996a99e29333c7e900b347f900b3c6d300ae93935507014217939d0702139f06024d8f81938192b3e7b701b3e6e6013a9abe9bb69ab3425a00931f060233cdab0133cc8a0193951200019293d2f2033366f601935d8d01135f8c01b3e2b200221de275221c329b336dbd01336cec017699b34c9b016a99e29393df8c01b347f900b3c6d3002e99a21ce265b3ecfc0113df0601c216e694b3e6e601258eb69aae94e66533cc8a01131f1c00135cfc0393dd0701336cec01ae99c217b3e7b701e299935f0601be9b4216b3c7f9003366f601939507028193329bcd8fb34c9b013e9b334c8b0133cdab0193558c01221c931d1d00336cbc00135dfd03a265336dbd01ea94939f1c00a58ef699ae9493dcfc038675b3ecfc01e299aa931699e693b3c7f9003346c90033c7e300ae9393d50701c217931d0602cd8f01923366b6013e9bb29a334c8b01939f0602b3c25a0093151c008192135cfc03b3e6f60193dd8201336cbc00a212c265131f0702369ab3e2b2011a9901933367e701334daa011699ba9b935f8d013346c900221d2e99a275b3cc9b01336dfd01935d0601421613df8c01ea943366b601a21cb3ecec01a58eb29aae94e675e693b3c25a0033c7e300939d120093d2f203135f0701b3e2b201ae9942173367e701969993df0601ba9bc21633c7e900b3e6f601931507020193369a4d8f334daa013a9ab3425a00f293b3cc9b01e29393d58201a212931f1d00139f1c00b3c6d300b3e2b200135dfd03c27593dcfc03336dfd01b3ecec01139f060281926a99b3e6e601b347f900b69a2e99c299826533cc8a019699e694135f8c0133c7e900221c258e939d0702336cec01ae938193935507014217931f0602b3e7b701e2934d8f01923366f601be9bb3c6d3003a9a329b33cdab0113df0601b3425a00c216b34c9b01935d8d01b3e6e60193951200221d93d2f20393df8c01336dbd01b69ab3e2b200a21ca275b3ecfc016a9933cc8a01c694e694b347f900131f1c00135cfc03258e93dd0701336cec01ae94c699c265c217b3e7b701e299935f0601be9b4216b3c7f9003366f601ae93939507028193329bcd8fb34c9b013e9b334c8b0193558c01221c336cbc0082651a9933cdab011699931d1d003346c900135dfd032e99e275336dbd01ea94a58eae94e675939f1c0093dcfc03ae99e299b3c7f90093d50701c217b3ecfc01931d0602939f0602cd8f01928192e6933366b601b3e6f6013e9b33c7e300b29a369a334c8b01131f0702b3c25a00334daa0193151c000193135cfc033367e70193dd8201935f8d01336cbc00a212e665221dba9bb3e2b201336dfd01b3cc9b011699ea9413df8c013346c900a58ea21cae94c275b3ecec01935d0601f2934216e6933366b60133c7e300b29aae93e265b3c25a00939d120093d2f203135f0701b3e2b201ae9942173367e701969993df0601ba9bc21633c7e900b3e6f601931507020193369a4d8f334daa013a9ab3425a0093d58201a212931f1d00b3e2b200135dfd03a265336dfd017699b3cc9b016a99e293139f1c00b347f900b3c6d3002e99aa99867593dcfc03b3ecec019699139f06028192e694b3e6e60133c7e900258eb69aae94935507014217939d070233cc8a014d8f8193b3e7b701135f8c013a9a221cbe9b336cec01b3425a00c293931f060233cdab01e29393951200019293d2f2033366f601935d8d01b3c6d300b3e2b200221dc265329b336dbd0113df0601c216b34c9b016a99b3e6e60193df8c01b347f900b69a2e99a21cc275b3ecfc0133cc8a01e694131f1c00135cfc03258e93dd0701336cec01ae94c2998265c217b3e7b701e299935f0601be9b4216b3c7f9003366f601ae93939507028193329bcd8fb34c9b013e9b334c8b0193558c01221c336cbc0086751699939f1c003346c90093dcfc032e99e665b3ecfc01e69333c7e300ae93e26533cdab01931d1d00ae99135dfd03336dbd01e299ea94b3c7f900a58e93d50701c217931d0602939f0602cd8f0192 [...]

2020-09-04 04:21 UTC, doitian commented on rfcs/0024-ckb-system-script-list/0024-ckb-system-script-list.md
> +| `tx_hash`   | `0xa05f28c9b867f8c5682039c10d8e864cf661685252aa74a008d255c33813bb81` |
Details of the deployment information is also listed here: https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0026-anyone-can-pay/0026-anyone-can-pay.md#notes

2020-09-04 04:29 UTC, doitian commented on rfcs/0024-ckb-system-script-list/0024-ckb-system-script-list.md
> +| `tx_hash`   | `0xc7813f6a415144643970c2e88e0bb6ca6a8edc5dd7c1022746f628284a9936d5` |
The cell 0xc7813f6a415144643970c2e88e0bb6ca6a8edc5dd7c1022746f628284a9936d5.outputs[0x0] matches the information in the [sUDT RFC](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0025-simple-udt/0025-simple-udt.md#notes), which type is

```
{
    "args": "0xcf37df53ec0eb890937879ad5587521f737dc3d95eb1c22194b958ecbcf39a8b",
    "codeHash": "0x00000000000000000000000000000000000000000000000000545950455f4944",
    "hashType": "type"
}
```

Its type hash is expected to be `0x5e7a36a77e68eecc013dfa2fe6a23f3b6c344b04005808694ae6dd45eea4cfd5` and can be verified by

```
echo '{ "args": "0xcf37df53ec0eb890937879ad5587521f737dc3d95eb1c22194b958ecbcf39a8b", "code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944", "hash_type": "type" }' > 0x5e7a36a77e68eecc013dfa2fe6a23f3b6c344b04005808694ae6dd45eea4cfd5.json
ckb-cli molecule encode --json-path 0x5e7a36a77e68eecc013dfa2fe6a23f3b6c344b04005808694ae6dd45eea4cfd5.json --type Script --output-type hash
```

2020-09-04 04:30 UTC, doitian submitted a review, later dismissed

2020-09-04 04:40 UTC, janx requested changes
- RFC links need to be updated as they have been merged;
- Source code links need to specify version;
- Need more information on the `dep_group` in secp256k1 and acp lock.

2020-09-04 05:20 UTC, quake submitted a review, later dismissed

2020-09-04 09:45 UTC, janx requested changes
Could you also add more explainations to the `dep_group` in SECP256K1/blake160 and SECP256K1/multisig?

2020-09-04 09:47 UTC, duanyytop commented
> Could you also add more explainations to the `dep_group` in SECP256K1/blake160 and SECP256K1/multisig?

OK. I will update it later.

2020-09-05 04:04 UTC, janx approved these changes

2020-09-05 04:06 UTC, xxuejie approved these changes

2020-09-05 08:04 UTC, zhangsoledad approved these changes

2020-09-07 01:01 UTC, merged