chore: finalize "RFC-0008: Serialization"
nervosnetwork/rfcs pull request #283
Opened 2021-12-21 09:25 UTC by yangby-cryptape

2021-12-21 09:39 UTC, janx requested changes
As this is a RFC on `Standards Track`, the status should be `Active` not `Final`.

2021-12-21 10:04 UTC, janx submitted a review, later dismissed

2021-12-22 09:54 UTC, zhangsoledad approved these changes

2021-12-22 10:39 UTC, janx approved these changes

2021-12-22 13:39 UTC, zhangsoledad approved these changes

2021-12-22 13:40 UTC, merged